import { AppShell, StatusBadge, formatDate } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, CheckCircle2, ClipboardCheck, FileEdit, PlayCircle } from "lucide-react";
import { useLocation } from "wouter";

export default function EvaluatorDashboard() {
  const [, setLocation] = useLocation(); const summary = trpc.evaluator.dashboard.useQuery(); const assignments = trpc.evaluator.assignments.useQuery();
  const metrics = [["Bekleyen", summary.data?.pending ?? 0, ClipboardCheck, "bg-amber-50 text-amber-700"], ["Taslak", summary.data?.drafts ?? 0, FileEdit, "bg-sky-50 text-sky-700"], ["Tamamlanan", summary.data?.completed ?? 0, CheckCircle2, "bg-emerald-50 text-emerald-700"], ["Son 3 gün", summary.data?.nearDue ?? 0, AlertTriangle, "bg-rose-50 text-rose-700"]] as const;
  const priority = assignments.data?.filter(item => item.nearDue && item.status !== "COMPLETED") ?? [];
  return <AppShell role="EVALUATOR"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-teal-700">Değerlendirici alanı</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-[#0b385d]">Çalışma özetiniz</h1><p className="mt-2 text-sm text-slate-500">Atanan eğitimleri değerlendirin ve taslaklarınızı tamamlayın.</p></div><Button onClick={() => setLocation("/evaluator/assignments")} className="gap-2 bg-[#0b385d] hover:bg-[#082d4c]"><PlayCircle className="h-4 w-4" /> Atamaları görüntüle</Button></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value, Icon, color]) => <Card key={label} className="border-slate-200 shadow-sm"><CardContent className="flex items-center justify-between p-5"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-3xl font-semibold text-[#0b385d]">{value}</p></div><div className={`grid h-12 w-12 place-items-center rounded-2xl ${color}`}><Icon className="h-5 w-5" /></div></CardContent></Card>)}</div><Card className="mt-6 border-slate-200 shadow-sm"><CardContent className="p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-rose-50 text-rose-600"><AlertTriangle className="h-5 w-5" /></div><div><p className="font-semibold text-[#0b385d]">Öncelikli değerlendirmeler</p><p className="text-sm text-slate-500">Son teslim tarihine üç gün veya daha az kalan atamalar.</p></div></div>{priority.length ? <div className="mt-5 grid gap-3">{priority.map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-rose-100 bg-rose-50/40 p-4"><div><p className="font-medium text-[#0b385d]">{item.training.title}</p><p className="mt-1 text-sm text-slate-600">Son tarih: <strong>{formatDate(item.dueDate)}</strong></p></div><div className="flex items-center gap-3"><StatusBadge status={item.status} /><Button size="sm" onClick={() => setLocation(`/evaluator/assignments/${item.id}/evaluate`)} className="bg-[#0b385d] hover:bg-[#082d4c]">Değerlendir</Button></div></div>)}</div> : <div className="mt-5 rounded-xl bg-slate-50 p-5 text-sm text-slate-500">Önümüzdeki üç gün içinde sonlanacak aktif değerlendirmeniz bulunmuyor.</div>}</CardContent></Card></AppShell>;
}
